_BASE_: [
  '../datasets/train1_table3.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/faster_rcnn_r50_fpn.yml',
  '_base_/faster_fpn_reader.yml',
]
weights: output/faster_rcnn_r50_fpn_1x_train1_table3/model_final
